import { jsPDF } from "jspdf";
import { format } from "date-fns";
import { getAge } from "@/hooks/useChildren";

export interface ReportData {
  child: { name: string; date_of_birth: string; is_premature: boolean | null; due_date: string | null };
  dateFrom: Date;
  dateTo: Date;
  milestones: any[];
  categories: any[];
  lastExportDate: string | null;
  feedings: any[];
  supplements: any[];
  diapers: any[];
  sleeps: any[];
  allergens: any[];
  illnesses: any[];
  medications: any[];
  pediatricianNotes: string;
}

interface PdfHelpers {
  doc: jsPDF;
  y: number;
  margin: number;
  contentW: number;
  pageW: number;
  checkPage: (needed: number) => void;
  heading: (text: string) => void;
  subheading: (text: string) => void;
  bodyText: (text: string, indent?: number) => void;
  spacer: (px?: number) => void;
}

function createHelpers(doc: jsPDF): PdfHelpers {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentW = pageW - margin * 2;
  const h: PdfHelpers = {
    doc, y: 20, margin, contentW, pageW,
    checkPage(needed: number) {
      if (h.y + needed > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        h.y = 20;
      }
    },
    heading(text: string) {
      h.checkPage(18);
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 30);
      doc.text(text.toUpperCase(), margin, h.y);
      h.y += 4;
      doc.setDrawColor(60, 60, 60);
      doc.setLineWidth(0.5);
      doc.line(margin, h.y, pageW - margin, h.y);
      h.y += 7;
    },
    subheading(text: string) {
      h.checkPage(12);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(50, 50, 50);
      doc.text(text, margin + 2, h.y);
      h.y += 5;
    },
    bodyText(text: string, indent = 0) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      const lines = doc.splitTextToSize(text, contentW - indent);
      h.checkPage(lines.length * 4 + 2);
      doc.text(lines, margin + indent, h.y);
      h.y += lines.length * 4 + 2;
    },
    spacer(px = 4) { h.y += px; },
  };
  return h;
}

// ── Title & Disclaimer ──
function renderTitleAndDisclaimer(h: PdfHelpers, data: ReportData) {
  const { doc, margin } = h;
  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text("Baby Steps — Pediatrician Report", margin, h.y);
  h.y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(`Generated: ${format(new Date(), "MMMM d, yyyy")}  |  Period: ${format(data.dateFrom, "MMM d, yyyy")} — ${format(data.dateTo, "MMM d, yyyy")}`, margin, h.y);
  h.y += 6;

  // Disclaimer box
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(margin, h.y, h.contentW, 14, 2, 2, "F");
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 100, 100);
  doc.text("DISCLAIMER: This report is generated by Baby Steps for informational purposes only. It is not a medical record.", margin + 3, h.y + 5);
  doc.text("All clinical interpretations and decisions should be made by the child's healthcare provider.", margin + 3, h.y + 10);
  h.y += 18;
}

// ── Child Info ──
function renderChildInfo(h: PdfHelpers, data: ReportData) {
  h.heading("Child Information");
  h.bodyText(`Name: ${data.child.name}`);
  h.bodyText(`Date of Birth: ${format(new Date(data.child.date_of_birth), "MMMM d, yyyy")}`);
  h.bodyText(`Age: ${getAge(data.child.date_of_birth, data.child.is_premature ?? false, data.child.due_date)}`);
  if (data.child.is_premature) h.bodyText(`Premature: Yes (Due date: ${data.child.due_date ?? "N/A"})`);
  h.spacer();
}

// ── Milestones ──
function renderMilestones(h: PdfHelpers, data: ReportData) {
  const milestones = data.milestones ?? [];
  const achieved = milestones.filter((m) => m.status === "achieved");
  const fromStr = format(data.dateFrom, "yyyy-MM-dd");
  const toStr = format(data.dateTo, "yyyy-MM-dd");
  const achievedInPeriod = achieved.filter((m) => m.achieved_at && m.achieved_at >= fromStr && m.achieved_at <= toStr);
  const previouslyAchieved = achieved.filter((m) => m.achieved_at && m.achieved_at < fromStr);

  h.heading("Milestones");
  h.bodyText(`Achieved in this period: ${achievedInPeriod.length}`);
  h.spacer(2);

  // Build category map
  const catMap: Record<string, string> = {};
  (data.categories ?? []).forEach((c: any) => { catMap[c.id] = c.name; });

  const domainOrder = ["Speech & Language", "Gross Motor", "Fine Motor", "Social & Emotional", "Cognitive", "Hearing & Vision"];

  const groupByDomain = (items: any[]) => {
    const groups: Record<string, any[]> = {};
    items.forEach((m) => {
      const catName = catMap[m.speech?.category_id] ?? "Other";
      if (!groups[catName]) groups[catName] = [];
      groups[catName].push(m);
    });
    return groups;
  };

  if (achievedInPeriod.length) {
    const groups = groupByDomain(achievedInPeriod);
    const sortedDomains = [...domainOrder.filter((d) => groups[d]), ...Object.keys(groups).filter((d) => !domainOrder.includes(d))];
    sortedDomains.forEach((domain) => {
      h.subheading(domain);
      groups[domain].forEach((m: any) => {
        h.bodyText(`✓ ${m.speech?.name ?? "Unknown"}${m.achieved_at ? ` — ${format(new Date(m.achieved_at), "MMM d, yyyy")}` : ""}`, 4);
      });
    });
  } else {
    h.bodyText("No new milestones achieved in this period.", 4);
  }

  if (previouslyAchieved.length) {
    h.spacer(2);
    h.subheading("Previously Achieved");
    const groups = groupByDomain(previouslyAchieved);
    const sortedDomains = [...domainOrder.filter((d) => groups[d]), ...Object.keys(groups).filter((d) => !domainOrder.includes(d))];
    sortedDomains.forEach((domain) => {
      h.bodyText(`${domain}: ${groups[domain].map((m: any) => m.speech?.name ?? "Unknown").join(", ")}`, 4);
    });
  }
  h.spacer();
}

// ── Feeding ──
function renderFeeding(h: PdfHelpers, data: ReportData) {
  const feedings = data.feedings ?? [];
  if (!feedings.length) return;

  h.heading("Feeding");

  const byType: Record<string, number> = {};
  let totalOz = 0, ozCount = 0, totalMin = 0, minCount = 0;
  feedings.forEach((f: any) => {
    byType[f.feeding_type] = (byType[f.feeding_type] || 0) + 1;
    if (f.amount_oz) { totalOz += Number(f.amount_oz); ozCount++; }
    if (f.duration_minutes) { totalMin += f.duration_minutes; minCount++; }
  });

  const days = Math.max(1, Math.ceil((data.dateTo.getTime() - data.dateFrom.getTime()) / 86400000));
  h.bodyText(`Total feedings: ${feedings.length}  |  Daily average: ${(feedings.length / days).toFixed(1)}/day`);
  h.bodyText(`Breakdown: ${Object.entries(byType).map(([k, v]) => `${k}: ${v}`).join(", ")}`);
  if (ozCount) h.bodyText(`Average bottle amount: ${(totalOz / ozCount).toFixed(1)} oz`);
  if (minCount) h.bodyText(`Average nursing duration: ${Math.round(totalMin / minCount)} min`);

  // Trend indicator
  if (ozCount >= 4) {
    const mid = Math.floor(feedings.length / 2);
    const firstHalf = feedings.slice(mid).filter((f: any) => f.amount_oz);
    const secondHalf = feedings.slice(0, mid).filter((f: any) => f.amount_oz);
    if (firstHalf.length && secondHalf.length) {
      const avgFirst = firstHalf.reduce((s: number, f: any) => s + Number(f.amount_oz), 0) / firstHalf.length;
      const avgSecond = secondHalf.reduce((s: number, f: any) => s + Number(f.amount_oz), 0) / secondHalf.length;
      const pctChange = ((avgSecond - avgFirst) / avgFirst) * 100;
      const trend = pctChange > 10 ? "↑ Increasing" : pctChange < -10 ? "↓ Decreasing" : "→ Stable";
      h.bodyText(`Volume trend: ${trend} (${pctChange > 0 ? "+" : ""}${pctChange.toFixed(0)}%)`);
    }
  }

  // Supplements
  const supplements = data.supplements ?? [];
  if (supplements.length) {
    h.spacer(2);
    h.subheading("Supplements");

    const primary = ["Vitamin D", "Iron"];
    const secondary = ["Fluoride", "Probiotics", "DHA", "B12"];

    const renderSuppList = (names: string[]) => {
      names.forEach((name) => {
        const supp = supplements.find((s: any) => s.name.toLowerCase() === name.toLowerCase());
        const active = supp?.is_active ? "Yes" : "No";
        const freq = supp?.frequency ?? "—";
        const form = supp?.form ?? "—";
        h.bodyText(`${name}: ${active}  |  Frequency: ${freq}  |  Form: ${form}`, 4);
      });
    };

    renderSuppList(primary);

    const hasSecondary = secondary.some((name) => supplements.find((s: any) => s.name.toLowerCase() === name.toLowerCase()));
    if (hasSecondary) {
      h.spacer(2);
      h.subheading("Situational Supplements");
      renderSuppList(secondary);
    }
  }
  h.spacer();
}

// ── Diapers ──
function renderDiapers(h: PdfHelpers, data: ReportData) {
  const diapers = data.diapers ?? [];
  if (!diapers.length) return;

  h.heading("Diapers");

  const wet = diapers.filter((d: any) => d.diaper_type === "wet");
  const dirty = diapers.filter((d: any) => d.diaper_type === "dirty");
  const days = Math.max(1, Math.ceil((data.dateTo.getTime() - data.dateFrom.getTime()) / 86400000));

  // Wet diaper callout
  if (wet.length) {
    h.subheading(`Hydration Indicator: ${wet.length} wet diapers (${(wet.length / days).toFixed(1)}/day)`);
  }

  h.bodyText(`Dirty diapers: ${dirty.length}  |  Daily average: ${(dirty.length / days).toFixed(1)}/day`);

  // Last 10 dirty diapers
  const last10 = dirty.slice(0, 10);
  if (last10.length) {
    h.spacer(2);
    h.subheading("Last 10 Dirty Diapers");
    last10.forEach((d: any) => {
      const date = format(new Date(d.logged_at), "MMM d, h:mm a");
      const parts = [d.consistency, d.color].filter(Boolean).join(", ");
      const flagColors = ["white", "pale", "red", "pink", "black"];
      const isFlagged = d.color && flagColors.some((fc) => d.color.toLowerCase().includes(fc));
      const flag = isFlagged ? " ⚠" : "";
      h.bodyText(`${date} — ${parts || "No details"}${d.notes ? ` (${d.notes})` : ""}${flag}`, 4);
    });
  }

  // Flagged entries (clinical colors only)
  const clinicallyFlagged = dirty.filter((d: any) => {
    if (!d.color) return false;
    const c = d.color.toLowerCase();
    return ["white", "pale", "red", "pink", "black"].some((fc) => c.includes(fc));
  });
  if (clinicallyFlagged.length) {
    h.spacer(2);
    h.subheading(`⚠ Clinically Significant Stool Colors (${clinicallyFlagged.length})`);
    clinicallyFlagged.slice(0, 10).forEach((d: any) => {
      h.bodyText(`${format(new Date(d.logged_at), "MMM d, h:mm a")} — Color: ${d.color}, Consistency: ${d.consistency ?? "—"}`, 4);
    });
  }
  h.spacer();
}

// ── Sleep ──
function renderSleep(h: PdfHelpers, data: ReportData) {
  const sleeps = data.sleeps ?? [];
  if (!sleeps.length) return;

  h.heading("Sleep");

  const nights = sleeps.filter((s: any) => s.sleep_type === "night");
  const naps = sleeps.filter((s: any) => s.sleep_type === "nap");
  const days = Math.max(1, Math.ceil((data.dateTo.getTime() - data.dateFrom.getTime()) / 86400000));

  const calcDuration = (s: any) => {
    if (s.duration_minutes) return s.duration_minutes;
    if (s.started_at && s.ended_at) {
      return Math.round((new Date(s.ended_at).getTime() - new Date(s.started_at).getTime()) / 60000);
    }
    return 0;
  };

  const totalSleepMin = sleeps.reduce((sum: number, s: any) => sum + calcDuration(s), 0);
  h.bodyText(`Total sleep sessions: ${sleeps.length}  |  Average daily sleep: ${(totalSleepMin / days / 60).toFixed(1)} hours/day`);

  // Longest stretch
  const longestMin = Math.max(...sleeps.map(calcDuration));
  if (longestMin > 0) {
    h.bodyText(`Longest single sleep stretch: ${Math.floor(longestMin / 60)}h ${longestMin % 60}m`);
  }

  // Night sleep stats
  if (nights.length) {
    const bedtimes = nights.map((s: any) => {
      const d = new Date(s.started_at);
      let mins = d.getHours() * 60 + d.getMinutes();
      if (mins < 360) mins += 1440; // after midnight → treat as late night
      return mins;
    });
    const avgBedtimeMin = Math.round(bedtimes.reduce((a: number, b: number) => a + b, 0) / bedtimes.length);
    const bedH = Math.floor((avgBedtimeMin % 1440) / 60);
    const bedM = (avgBedtimeMin % 1440) % 60;
    const bedAMPM = bedH >= 12 ? "PM" : "AM";
    const bedH12 = bedH > 12 ? bedH - 12 : bedH === 0 ? 12 : bedH;

    h.bodyText(`Average bedtime: ${bedH12}:${String(bedM).padStart(2, "0")} ${bedAMPM}`);

    const wakeTimes = nights.filter((s: any) => s.ended_at).map((s: any) => {
      const d = new Date(s.ended_at);
      return d.getHours() * 60 + d.getMinutes();
    });
    if (wakeTimes.length) {
      const avgWakeMin = Math.round(wakeTimes.reduce((a: number, b: number) => a + b, 0) / wakeTimes.length);
      const wakeH = Math.floor(avgWakeMin / 60);
      const wakeM = avgWakeMin % 60;
      const wakeAMPM = wakeH >= 12 ? "PM" : "AM";
      const wakeH12 = wakeH > 12 ? wakeH - 12 : wakeH === 0 ? 12 : wakeH;
      h.bodyText(`Average wake time: ${wakeH12}:${String(wakeM).padStart(2, "0")} ${wakeAMPM}`);
    }

    const avgNightDur = nights.reduce((s: number, n: any) => s + calcDuration(n), 0) / nights.length;
    h.bodyText(`Average night sleep: ${Math.floor(avgNightDur / 60)}h ${Math.round(avgNightDur % 60)}m`);

    // Night wakings estimate: multiple night sessions per calendar day = wakings
    const nightsByDate: Record<string, number> = {};
    nights.forEach((s: any) => {
      const dateKey = format(new Date(s.started_at), "yyyy-MM-dd");
      nightsByDate[dateKey] = (nightsByDate[dateKey] || 0) + 1;
    });
    const nightDays = Object.keys(nightsByDate).length;
    const totalWakings = Object.values(nightsByDate).reduce((s, c) => s + Math.max(0, c - 1), 0);
    if (nightDays > 0) {
      h.bodyText(`Average night wakings: ${(totalWakings / nightDays).toFixed(1)}/night`);
    }
  }

  // Nap stats
  if (naps.length) {
    h.bodyText(`Average naps/day: ${(naps.length / days).toFixed(1)}`);
    const avgNapDur = naps.reduce((s: number, n: any) => s + calcDuration(n), 0) / naps.length;
    h.bodyText(`Average nap duration: ${Math.floor(avgNapDur / 60)}h ${Math.round(avgNapDur % 60)}m`);
  }

  // Quality
  const qualities: Record<string, number> = {};
  sleeps.forEach((s: any) => { if (s.quality) qualities[s.quality] = (qualities[s.quality] || 0) + 1; });
  if (Object.keys(qualities).length) {
    h.bodyText(`Quality: ${Object.entries(qualities).map(([k, v]) => `${k}: ${v}`).join(", ")}`);
  }
  h.spacer();
}

// ── Illness & Medications ──
function renderIllness(h: PdfHelpers, data: ReportData) {
  const illnesses = data.illnesses ?? [];
  const medications = data.medications ?? [];
  if (!illnesses.length && !medications.length) return;

  h.heading("Illness & Medications");

  if (illnesses.length) {
    illnesses.forEach((ill: any) => {
      const end = ill.end_date ? format(new Date(ill.end_date), "MMM d") : "Ongoing";
      h.bodyText(`${ill.illness_name}: ${format(new Date(ill.start_date), "MMM d")} — ${end}${ill.notes ? ` (${ill.notes})` : ""}`);
      const relatedMeds = medications.filter((m: any) => m.illness_log_id === ill.id);
      relatedMeds.forEach((m: any) => {
        h.bodyText(`Rx: ${m.medication_name}${m.dose ? `, ${m.dose}` : ""}${m.frequency ? `, ${m.frequency}` : ""}`, 6);
      });
    });
  }

  // Standalone medications (not linked to an illness)
  const standaloneMeds = medications.filter((m: any) => !m.illness_log_id);
  if (standaloneMeds.length) {
    h.subheading("Other Medications");
    standaloneMeds.forEach((m: any) => {
      const end = m.end_date ? format(new Date(m.end_date), "MMM d") : "Ongoing";
      h.bodyText(`${m.medication_name}: ${format(new Date(m.start_date), "MMM d")} — ${end}${m.dose ? ` (${m.dose})` : ""}${m.frequency ? `, ${m.frequency}` : ""}`, 4);
    });
  }
  h.spacer();
}

// ── Allergens ──
function renderAllergens(h: PdfHelpers, data: ReportData) {
  const allergens = data.allergens ?? [];
  if (!allergens.length) return;

  h.heading("Allergen Introductions");

  const statusLabel = (s: string) => {
    const map: Record<string, string> = {
      not_started: "Not Started",
      in_progress: "In Progress",
      completed: "Completed / Safe",
      safe: "Completed / Safe",
      active: "In Progress",
      reaction_observed: "Reaction Noted",
    };
    return map[s] ?? s;
  };

  const safe = allergens.filter((a: any) => ["completed", "safe"].includes(a.status));
  const reacted = allergens.filter((a: any) => a.status === "reaction_observed");
  const inProgress = allergens.filter((a: any) => ["in_progress", "active"].includes(a.status));

  h.bodyText(`Total: ${allergens.length}  |  Completed: ${safe.length}  |  Reactions: ${reacted.length}  |  In Progress: ${inProgress.length}`);
  h.spacer(2);

  allergens.forEach((a: any) => {
    h.bodyText(`${a.allergens?.name ?? "Unknown"}: ${statusLabel(a.status)}${a.notes ? ` — ${a.notes}` : ""}`, 4);
  });
  h.spacer();
}

// ── Parent Notes ──
function renderParentNotes(h: PdfHelpers, notes: string) {
  if (!notes.trim()) return;
  h.heading("Parent Notes & Reminders");
  h.bodyText(notes.trim());
  h.spacer();
}

// ── Footer ──
function renderFooter(h: PdfHelpers) {
  h.checkPage(12);
  h.doc.setDrawColor(180);
  h.doc.line(h.margin, h.y, h.pageW - h.margin, h.y);
  h.y += 5;
  h.doc.setFontSize(7);
  h.doc.setFont("helvetica", "italic");
  h.doc.setTextColor(140, 140, 140);
  h.doc.text("Generated by Tiny Sprout — for informational purposes only. Not a substitute for professional medical advice.", h.margin, h.y);
}

// ── Main Export ──
export function generatePediatricianReport(data: ReportData, sections: Set<string>): jsPDF {
  const doc = new jsPDF();
  const h = createHelpers(doc);

  renderTitleAndDisclaimer(h, data);
  renderChildInfo(h, data);
  if (sections.has("speech")) renderMilestones(h, data);
  if (sections.has("feeding")) renderFeeding(h, data);
  if (sections.has("diapers")) renderDiapers(h, data);
  if (sections.has("sleep")) renderSleep(h, data);
  if (sections.has("illness")) renderIllness(h, data);
  if (sections.has("allergens")) renderAllergens(h, data);
  renderParentNotes(h, data.pediatricianNotes);
  renderFooter(h);

  return doc;
}
