import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Check, MoreHorizontal, ChevronDown, Sparkles, ChevronRight, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { openVisitPrep } from "@/lib/visitPrepOpener";
import { useNextSteps } from "@/hooks/useNextSteps";
import { useNextStepPeek } from "@/hooks/useNextStepPeek";
import { hasFeedActions, type NextStepItem, type NextStepDomain } from "@/lib/nextSteps";
import { getSkill, type SkillId } from "@/lib/skills";

interface ChildLite {
  id: string;
  name: string;
  date_of_birth: string;
  is_premature?: boolean | null;
  due_date?: string | null;
  is_expected?: boolean | null;
  next_appointment?: string | null;
}

const DOMAIN_DOT: Record<NextStepDomain, string> = {
  sleep: "bg-sleep",
  milestone: "bg-milestones",
  finance: "bg-finance",
  health: "bg-primary",
};

const DOMAIN_TINT: Record<NextStepDomain, string> = {
  sleep: "bg-sleep-bg",
  milestone: "bg-milestones-bg",
  finance: "bg-finance-bg",
  health: "bg-muted/40",
};

const VISIBLE_ROWS = 3;

function PeekPanel({
  item,
  childId,
  childName,
  open,
}: {
  item: NextStepItem;
  childId?: string;
  childName?: string;
  open: boolean;
}) {
  const peek = useNextStepPeek({ childId, item, enabled: open });
  const firstName = childName?.trim().split(/\s+/)[0];

  return (
    <div
      className={cn(
        "rounded-xl p-3 mt-1",
        DOMAIN_TINT[item.domain] ?? "bg-muted/40",
      )}
    >
      {peek.isLoading ? (
        <div className="flex items-center gap-2">
          <Loader2 className="w-4 h-4 animate-spin text-muted-foreground" />
          <span className="text-sm text-muted-foreground">Thinking of an idea…</span>
        </div>
      ) : peek.data?.answer ? (
        <div className="space-y-1.5">
          <div className="flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5 text-muted-foreground shrink-0" />
            <span className="text-xs text-muted-foreground">
              {firstName
                ? `Generated for ${firstName}`
                : "Generated by Grace Flare AI"}
            </span>
          </div>
          <p className="text-sm leading-snug text-foreground text-left">
            {peek.data.answer}
          </p>
        </div>
      ) : (
        <p className="text-sm text-muted-foreground text-left">
          No suggestion to show right now — check back a little later.
        </p>
      )}

      <p className="text-[11px] text-muted-foreground italic mt-2">
        General guidance — not medical advice.
      </p>
    </div>
  );
}

function NextStepRow({
  item,
  childId,
  childName,
  onComplete,
  onSnooze,
  onDismiss,
}: {
  item: NextStepItem;
  childId?: string;
  childName?: string;
  onComplete: (item: NextStepItem) => void;
  onSnooze: (item: NextStepItem) => void;
  onDismiss: (item: NextStepItem) => void;
}) {
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const isAsk = item.deeplink.kind === "ask";
  const canAct = hasFeedActions(item);

  const handleOpen = () => {
    const { kind, target } = item.deeplink;
    if (kind === "sheet" && target === "visit-prep") {
      openVisitPrep();
      return;
    }
    if (kind === "route") navigate(target);
  };

  const titleBlock = (
    <>
      <span
        className={cn(
          "w-2 h-2 rounded-full shrink-0",
          DOMAIN_DOT[item.domain],
        )}
        aria-hidden
      />
      <span className="flex-1 min-w-0">
        <span className="block font-sans font-semibold text-sm truncate">
          {item.title}
        </span>
        <span
          className={cn(
            "block text-xs truncate mt-0.5",
            item.tier === "redflag"
              ? "text-destructive"
              : item.tier === "soon"
                ? "text-accent"
                : "text-muted-foreground",
          )}
        >
          {item.affinityLabel
            ? `${item.meta} · picked for a ${item.affinityLabel} fan`
            : item.meta}
        </span>
      </span>
      {item.tier === "soon" && (
        <Badge
          variant="outline"
          className="shrink-0 text-accent border-accent/40 text-xs"
        >
          Soon
        </Badge>
      )}
    </>
  );

  const completeAndMore = !canAct ? null : (
    <>
      <button
        type="button"
        onClick={() => onComplete(item)}
        aria-label={
          item.domain === "milestone"
            ? "Done for today"
            : `Mark "${item.title}" done`
        }
        className="touch-target shrink-0 flex items-center justify-center text-muted-foreground hover:text-primary transition-colors"
      >
        <Check className="w-5 h-5" />
      </button>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <button
            type="button"
            aria-label={`More actions for "${item.title}"`}
            className="touch-target shrink-0 flex items-center justify-center text-muted-foreground hover:text-foreground transition-colors"
          >
            <MoreHorizontal className="w-5 h-5" />
          </button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={() => onSnooze(item)}>
            Snooze
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => onDismiss(item)}>
            Not relevant
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </>
  );

  if (isAsk) {
    const skill = getSkill(item.deeplink.forceSkill as SkillId);
    return (
      <Collapsible open={open} onOpenChange={setOpen}>
        <div className="flex items-stretch min-h-[64px]">
          <CollapsibleTrigger asChild>
            <button
              type="button"
              aria-label={`Show AI suggestion for ${item.title}`}
              className="flex flex-1 items-center gap-3 py-3 pl-1 pr-2 text-left min-w-0 touch-target active:opacity-70 transition-opacity"
            >
              {titleBlock}
              <span
                className={cn(
                  "inline-flex items-center gap-1 shrink-0 rounded-full px-2 py-0.5 text-xs font-semibold",
                  skill?.color ?? "bg-primary/10 text-primary",
                )}
              >
                <Sparkles className="w-3.5 h-3.5" />
                Ask AI
              </span>
              <ChevronDown
                className={cn(
                  "w-4 h-4 text-muted-foreground shrink-0 transition-transform",
                  open && "rotate-180",
                )}
              />
            </button>
          </CollapsibleTrigger>
          {completeAndMore}
        </div>
        <CollapsibleContent>
          <PeekPanel
            item={item}
            childId={childId}
            childName={childName}
            open={open}
          />
        </CollapsibleContent>
      </Collapsible>
    );
  }

  return (
    <div className="flex items-stretch min-h-[64px]">
      <button
        type="button"
        onClick={handleOpen}
        className="flex flex-1 items-center gap-3 py-3 pl-1 pr-2 text-left min-w-0 touch-target active:opacity-70 transition-opacity"
      >
        {titleBlock}
        <ChevronRight className="w-4 h-4 text-muted-foreground shrink-0" />
      </button>
      {completeAndMore}
    </div>
  );
}

export function NextStepFeed({
  activeChild,
  embedded = false,
}: {
  activeChild: ChildLite | null;
  embedded?: boolean;
}) {
  const { items, isLoading, isError, complete, snooze, dismiss } =
    useNextSteps(activeChild);
  const [expanded, setExpanded] = useState(false);

  if (!activeChild) return null;

  const Inner = ({ children }: { children: React.ReactNode }) => (
    <>
      <div className="mb-1">
        <h2 className="font-display font-bold text-base">Next steps</h2>
        <p className="text-xs text-muted-foreground">
          Sorted by what's most time-sensitive.
        </p>
      </div>
      {children}
    </>
  );

  const Shell = ({ children }: { children: React.ReactNode }) =>
    embedded ? (
      <div>
        <Inner>{children}</Inner>
      </div>
    ) : (
      <Card className="border-0 bg-card rounded-2xl shadow-sm">
        <CardContent className="p-4">
          <Inner>{children}</Inner>
        </CardContent>
      </Card>
    );

  if (isLoading) {
    return (
      <Shell>
        <div className="mt-2 divide-y divide-border">
          {[0, 1, 2].map((i) => (
            <div key={i} className="flex items-center gap-3 min-h-[64px] py-3">
              <Skeleton className="w-2 h-2 rounded-full" />
              <div className="flex-1 space-y-2">
                <Skeleton className="h-4 w-3/5" />
                <Skeleton className="h-3 w-2/5" />
              </div>
            </div>
          ))}
        </div>
      </Shell>
    );
  }

  // Error stays calm — one neutral row, never an alarm.
  if (isError) {
    return (
      <Shell>
        <p className="text-sm text-muted-foreground py-3">
          We couldn't load your next steps. Pull down to retry.
        </p>
      </Shell>
    );
  }

  if (items.length === 0) {
    return (
      <Shell>
        <p className="text-sm font-semibold py-1">Nothing needs you right now.</p>
        <p className="text-xs text-muted-foreground">
          That's a good place to be. When something's coming up, you'll see it
          here first.
        </p>
      </Shell>
    );
  }

  const visible = items.slice(0, VISIBLE_ROWS);
  const overflow = items.slice(VISIBLE_ROWS);

  const rowProps = {
    childId: activeChild.id,
    childName: activeChild.name,
    onComplete: complete,
    onSnooze: snooze,
    onDismiss: dismiss,
  };

  const showAdviceDisclaimer = items.some(
    (item) =>
      item.domain === "finance" ||
      item.domain === "health" ||
      item.deeplink.kind === "ask",
  );

  return (
    <Shell>
      <div className="mt-1 divide-y divide-border" aria-live="polite">
        {visible.map((item) => (
          <NextStepRow key={item.id} item={item} {...rowProps} />
        ))}

        {overflow.length > 0 && (
          <Collapsible open={expanded} onOpenChange={setExpanded}>
            <CollapsibleContent>
              <div className="divide-y divide-border">
                {overflow.map((item) => (
                  <NextStepRow key={item.id} item={item} {...rowProps} />
                ))}
              </div>
            </CollapsibleContent>
            <CollapsibleTrigger asChild>
              <Button
                variant="ghost"
                className="w-full touch-target text-sm text-muted-foreground gap-1"
              >
                {expanded ? "See less" : `See ${overflow.length} more`}
                <ChevronDown
                  className={cn(
                    "w-4 h-4 transition-transform",
                    expanded && "rotate-180",
                  )}
                />
              </Button>
            </CollapsibleTrigger>
          </Collapsible>
        )}
      </div>
      {showAdviceDisclaimer && (
        <p className="text-[11px] text-muted-foreground italic mt-3">
          General guidance and reminders — not medical or financial advice.
        </p>
      )}
    </Shell>
  );
}
